[platformio]
default_envs = esp32-3248s035
description = PlatformIO project demo using ESP32-3248S035 BSP

[lvgl]
build_flags =
	-DLV_CONF_INCLUDE_SIMPLE=1
	-DLV_CONF_SKIP=1
	-DLV_COLOR_DEPTH=16
	-DLV_USE_LOG=1
	-DLV_LOG_LEVEL=LV_LOG_LEVEL_INFO

[env:esp32-3248s035]
platform = espressif32
framework = arduino
board = esp32-3248S035R
;board_build.partitions = $PROJECT_DIR/etc/esp32/partitions.csv
board_build.partitions = C:/Users/Agus/Documents/Proyectos/CascoTermico/firmware/ESP32-3248S035/examples/platformio/etc/esp32/partitions.csv
build_flags =
	${lvgl.build_flags}
;	-D CORE_DEBUG_LEVEL=5
lib_deps =
	 https://github.com/ardnew/ESP32-3248S035
	 ;file://../../ESP32-3248S035 ;ESP32-3248S035=symlink://../../
monitor_speed = 115200
upload_port = COM7
extra_scripts =
	pre:etc/platformio/middleware.py
